/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.CartItems;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CartItemsRecord extends UpdatableRecordImpl<CartItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.cart_items.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.cart_items.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.cart_items.cart_id</code>.
     */
    public void setCartId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.cart_items.cart_id</code>.
     */
    public Integer getCartId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.cart_items.product_id</code>.
     */
    public void setProductId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.cart_items.product_id</code>.
     */
    public UUID getProductId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.cart_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.cart_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.cart_items.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.cart_items.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.cart_items.added_at</code>.
     */
    public void setAddedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.cart_items.added_at</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.cart_items.modified_at</code>.
     */
    public void setModifiedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.cart_items.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CartItemsRecord
     */
    public CartItemsRecord() {
        super(CartItems.CART_ITEMS);
    }

    /**
     * Create a detached, initialised CartItemsRecord
     */
    public CartItemsRecord(Long id, Integer cartId, UUID productId, Integer quantity, BigDecimal price, LocalDateTime addedAt, LocalDateTime modifiedAt) {
        super(CartItems.CART_ITEMS);

        setId(id);
        setCartId(cartId);
        setProductId(productId);
        setQuantity(quantity);
        setPrice(price);
        setAddedAt(addedAt);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
