/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.Categories;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoriesRecord extends UpdatableRecordImpl<CategoriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.categories.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.categories.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.categories.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.categories.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.categories.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.categories.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.categories.parent_id</code>.
     */
    public void setParentId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.categories.parent_id</code>.
     */
    public Integer getParentId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.categories.image_id</code>.
     */
    public void setImageId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.categories.image_id</code>.
     */
    public UUID getImageId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoriesRecord
     */
    public CategoriesRecord() {
        super(Categories.CATEGORIES);
    }

    /**
     * Create a detached, initialised CategoriesRecord
     */
    public CategoriesRecord(Integer id, String name, String description, Integer parentId, UUID imageId) {
        super(Categories.CATEGORIES);

        setId(id);
        setName(name);
        setDescription(description);
        setParentId(parentId);
        setImageId(imageId);
        resetChangedOnNotNull();
    }
}
