/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.enums.OrderStatus;
import com.sendiy.common.jooq.tables.Orders;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.orders.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.orders.cart_id</code>.
     */
    public void setCartId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.cart_id</code>.
     */
    public Long getCartId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.orders.status</code>.
     */
    public void setStatus(OrderStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.status</code>.
     */
    public OrderStatus getStatus() {
        return (OrderStatus) get(3);
    }

    /**
     * Setter for <code>public.orders.total</code>.
     */
    public void setTotal(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.orders.total</code>.
     */
    public BigDecimal getTotal() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.orders.shipping_address</code>.
     */
    public void setShippingAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.orders.shipping_address</code>.
     */
    public String getShippingAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.orders.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.orders.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.orders.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.orders.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.orders.modified_at</code>.
     */
    public void setModifiedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.orders.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(UUID id, UUID userId, Long cartId, OrderStatus status, BigDecimal total, String shippingAddress, LocalDateTime createdAt, UUID createdBy, LocalDateTime modifiedAt) {
        super(Orders.ORDERS);

        setId(id);
        setUserId(userId);
        setCartId(cartId);
        setStatus(status);
        setTotal(total);
        setShippingAddress(shippingAddress);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        resetChangedOnNotNull();
    }
}
