/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.OrderItems;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItemsRecord extends UpdatableRecordImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_items.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_items.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public void setOrderId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public UUID getOrderId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.order_items.product_id</code>.
     */
    public void setProductId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_items.product_id</code>.
     */
    public UUID getProductId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.order_items.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.order_items.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.order_items.added_at</code>.
     */
    public void setAddedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.order_items.added_at</code>.
     */
    public LocalDateTime getAddedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(UUID id, UUID orderId, UUID productId, Integer quantity, BigDecimal price, LocalDateTime addedAt) {
        super(OrderItems.ORDER_ITEMS);

        setId(id);
        setOrderId(orderId);
        setProductId(productId);
        setQuantity(quantity);
        setPrice(price);
        setAddedAt(addedAt);
        resetChangedOnNotNull();
    }
}
