/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.ProductImages;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductImagesRecord extends UpdatableRecordImpl<ProductImagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.product_images.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.product_images.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.product_images.medium_id</code>.
     */
    public void setMediumId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.product_images.medium_id</code>.
     */
    public Long getMediumId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.product_images.small_id</code>.
     */
    public void setSmallId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.product_images.small_id</code>.
     */
    public Long getSmallId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.product_images.product_id</code>.
     */
    public void setProductId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.product_images.product_id</code>.
     */
    public UUID getProductId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.product_images.file_id</code>.
     */
    public void setFileId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.product_images.file_id</code>.
     */
    public UUID getFileId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.product_images.is_primary</code>.
     */
    public void setIsPrimary(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.product_images.is_primary</code>.
     */
    public Boolean getIsPrimary() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductImagesRecord
     */
    public ProductImagesRecord() {
        super(ProductImages.PRODUCT_IMAGES);
    }

    /**
     * Create a detached, initialised ProductImagesRecord
     */
    public ProductImagesRecord(Long id, Long mediumId, Long smallId, UUID productId, UUID fileId, Boolean isPrimary) {
        super(ProductImages.PRODUCT_IMAGES);

        setId(id);
        setMediumId(mediumId);
        setSmallId(smallId);
        setProductId(productId);
        setFileId(fileId);
        setIsPrimary(isPrimary);
        resetChangedOnNotNull();
    }
}
