/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.Products;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.products.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.products.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.products.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.products.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.products.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.products.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.products.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.products.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.products.price</code>.
     */
    public void setPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.products.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.products.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.products.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.products.shop_id</code>.
     */
    public void setShopId(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.products.shop_id</code>.
     */
    public UUID getShopId() {
        return (UUID) get(6);
    }

    /**
     * Setter for <code>public.products.category_id</code>.
     */
    public void setCategoryId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.products.category_id</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.products.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.products.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.products.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.products.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.products.modified_at</code>.
     */
    public void setModifiedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.products.modified_at</code>.
     */
    public LocalDateTime getModifiedAt() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.products.modified_by</code>.
     */
    public void setModifiedBy(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.products.modified_by</code>.
     */
    public UUID getModifiedBy() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.products.deleted_date</code>.
     */
    public void setDeletedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.products.deleted_date</code>.
     */
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.products.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.products.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(UUID id, String title, UUID userId, String description, BigDecimal price, Integer quantity, UUID shopId, Integer categoryId, LocalDateTime createdAt, UUID createdBy, LocalDateTime modifiedAt, UUID modifiedBy, LocalDateTime deletedDate, Boolean isActive) {
        super(Products.PRODUCTS);

        setId(id);
        setTitle(title);
        setUserId(userId);
        setDescription(description);
        setPrice(price);
        setQuantity(quantity);
        setShopId(shopId);
        setCategoryId(categoryId);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        setDeletedDate(deletedDate);
        setIsActive(isActive);
        resetChangedOnNotNull();
    }
}
