/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.Reviews;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReviewsRecord extends UpdatableRecordImpl<ReviewsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.reviews.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.reviews.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.reviews.product_id</code>.
     */
    public void setProductId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.reviews.product_id</code>.
     */
    public UUID getProductId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.reviews.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.reviews.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.reviews.rating</code>.
     */
    public void setRating(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.reviews.rating</code>.
     */
    public Short getRating() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.reviews.comment</code>.
     */
    public void setComment(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.reviews.comment</code>.
     */
    public String getComment() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.reviews.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.reviews.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.reviews.created_by</code>.
     */
    public void setCreatedBy(UUID value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.reviews.created_by</code>.
     */
    public UUID getCreatedBy() {
        return (UUID) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReviewsRecord
     */
    public ReviewsRecord() {
        super(Reviews.REVIEWS);
    }

    /**
     * Create a detached, initialised ReviewsRecord
     */
    public ReviewsRecord(Long id, UUID productId, UUID userId, Short rating, String comment, LocalDateTime createdAt, UUID createdBy) {
        super(Reviews.REVIEWS);

        setId(id);
        setProductId(productId);
        setUserId(userId);
        setRating(rating);
        setComment(comment);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
