/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.tables.ShippingAddress;

import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShippingAddressRecord extends UpdatableRecordImpl<ShippingAddressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.shipping_address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.shipping_address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.shipping_address.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.shipping_address.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.shipping_address.recipient_name</code>.
     */
    public void setRecipientName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.shipping_address.recipient_name</code>.
     */
    public String getRecipientName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.shipping_address.region</code>.
     */
    public void setRegion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.shipping_address.region</code>.
     */
    public String getRegion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.shipping_address.district</code>.
     */
    public void setDistrict(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.shipping_address.district</code>.
     */
    public String getDistrict() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.shipping_address.city</code>.
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.shipping_address.city</code>.
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.shipping_address.street</code>.
     */
    public void setStreet(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.shipping_address.street</code>.
     */
    public String getStreet() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.shipping_address.home_number</code>.
     */
    public void setHomeNumber(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.shipping_address.home_number</code>.
     */
    public Integer getHomeNumber() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShippingAddressRecord
     */
    public ShippingAddressRecord() {
        super(ShippingAddress.SHIPPING_ADDRESS);
    }

    /**
     * Create a detached, initialised ShippingAddressRecord
     */
    public ShippingAddressRecord(Long id, UUID userId, String recipientName, String region, String district, String city, String street, Integer homeNumber) {
        super(ShippingAddress.SHIPPING_ADDRESS);

        setId(id);
        setUserId(userId);
        setRecipientName(recipientName);
        setRegion(region);
        setDistrict(district);
        setCity(city);
        setStreet(street);
        setHomeNumber(homeNumber);
        resetChangedOnNotNull();
    }
}
