/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables.records;


import com.sendiy.common.jooq.enums.PaymentStatus;
import com.sendiy.common.jooq.tables.Transactions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionsRecord extends UpdatableRecordImpl<TransactionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transactions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.transactions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.transactions.order_id</code>.
     */
    public void setOrderId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.transactions.order_id</code>.
     */
    public UUID getOrderId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.transactions.payment_method</code>.
     */
    public void setPaymentMethod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.transactions.payment_method</code>.
     */
    public String getPaymentMethod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.transactions.status</code>.
     */
    public void setStatus(PaymentStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.transactions.status</code>.
     */
    public PaymentStatus getStatus() {
        return (PaymentStatus) get(3);
    }

    /**
     * Setter for <code>public.transactions.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.transactions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionsRecord
     */
    public TransactionsRecord() {
        super(Transactions.TRANSACTIONS);
    }

    /**
     * Create a detached, initialised TransactionsRecord
     */
    public TransactionsRecord(UUID id, UUID orderId, String paymentMethod, PaymentStatus status, LocalDateTime createdAt) {
        super(Transactions.TRANSACTIONS);

        setId(id);
        setOrderId(orderId);
        setPaymentMethod(paymentMethod);
        setStatus(status);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
