/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables;


import com.sendiy.common.jooq.Keys;
import com.sendiy.common.jooq.Public;
import com.sendiy.common.jooq.tables.CartItems.CartItemsPath;
import com.sendiy.common.jooq.tables.Orders.OrdersPath;
import com.sendiy.common.jooq.tables.Users.UsersPath;
import com.sendiy.common.jooq.tables.records.CartsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Carts extends TableImpl<CartsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.carts</code>
     */
    public static final Carts CARTS = new Carts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CartsRecord> getRecordType() {
        return CartsRecord.class;
    }

    /**
     * The column <code>public.carts.id</code>.
     */
    public final TableField<CartsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.carts.user_id</code>.
     */
    public final TableField<CartsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.carts.created_at</code>.
     */
    public final TableField<CartsRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.carts.created_by</code>.
     */
    public final TableField<CartsRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    private Carts(Name alias, Table<CartsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Carts(Name alias, Table<CartsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.carts</code> table reference
     */
    public Carts(String alias) {
        this(DSL.name(alias), CARTS);
    }

    /**
     * Create an aliased <code>public.carts</code> table reference
     */
    public Carts(Name alias) {
        this(alias, CARTS);
    }

    /**
     * Create a <code>public.carts</code> table reference
     */
    public Carts() {
        this(DSL.name("carts"), null);
    }

    public <O extends Record> Carts(Table<O> path, ForeignKey<O, CartsRecord> childPath, InverseForeignKey<O, CartsRecord> parentPath) {
        super(path, childPath, parentPath, CARTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CartsPath extends Carts implements Path<CartsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CartsPath(Table<O> path, ForeignKey<O, CartsRecord> childPath, InverseForeignKey<O, CartsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CartsPath(Name alias, Table<CartsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CartsPath as(String alias) {
            return new CartsPath(DSL.name(alias), this);
        }

        @Override
        public CartsPath as(Name alias) {
            return new CartsPath(alias, this);
        }

        @Override
        public CartsPath as(Table<?> alias) {
            return new CartsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<CartsRecord, Long> getIdentity() {
        return (Identity<CartsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CartsRecord> getPrimaryKey() {
        return Keys.CARTS_PKEY;
    }

    @Override
    public List<ForeignKey<CartsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CARTS__CARTS_USER_ID_FKEY, Keys.CARTS__CARTS_CREATED_BY_FKEY);
    }

    private transient UsersPath _cartsUserIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>carts_user_id_fkey</code> key.
     */
    public UsersPath cartsUserIdFkey() {
        if (_cartsUserIdFkey == null)
            _cartsUserIdFkey = new UsersPath(this, Keys.CARTS__CARTS_USER_ID_FKEY, null);

        return _cartsUserIdFkey;
    }

    private transient UsersPath _cartsCreatedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>carts_created_by_fkey</code> key.
     */
    public UsersPath cartsCreatedByFkey() {
        if (_cartsCreatedByFkey == null)
            _cartsCreatedByFkey = new UsersPath(this, Keys.CARTS__CARTS_CREATED_BY_FKEY, null);

        return _cartsCreatedByFkey;
    }

    private transient CartItemsPath _cartItems;

    /**
     * Get the implicit to-many join path to the <code>public.cart_items</code>
     * table
     */
    public CartItemsPath cartItems() {
        if (_cartItems == null)
            _cartItems = new CartItemsPath(this, null, Keys.CART_ITEMS__CART_ITEMS_CART_ID_FKEY.getInverseKey());

        return _cartItems;
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit to-many join path to the <code>public.orders</code>
     * table
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, null, Keys.ORDERS__ORDERS_CART_ID_FKEY.getInverseKey());

        return _orders;
    }

    @Override
    public Carts as(String alias) {
        return new Carts(DSL.name(alias), this);
    }

    @Override
    public Carts as(Name alias) {
        return new Carts(alias, this);
    }

    @Override
    public Carts as(Table<?> alias) {
        return new Carts(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Carts rename(String name) {
        return new Carts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Carts rename(Name name) {
        return new Carts(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Carts rename(Table<?> name) {
        return new Carts(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts where(Condition condition) {
        return new Carts(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Carts where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Carts where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Carts where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Carts where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Carts whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
