/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq.tables;


import com.sendiy.common.jooq.Keys;
import com.sendiy.common.jooq.Public;
import com.sendiy.common.jooq.enums.OrderStatus;
import com.sendiy.common.jooq.tables.Carts.CartsPath;
import com.sendiy.common.jooq.tables.OrderItems.OrderItemsPath;
import com.sendiy.common.jooq.tables.Transactions.TransactionsPath;
import com.sendiy.common.jooq.tables.Users.UsersPath;
import com.sendiy.common.jooq.tables.records.OrdersRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orders extends TableImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.orders</code>
     */
    public static final Orders ORDERS = new Orders();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrdersRecord> getRecordType() {
        return OrdersRecord.class;
    }

    /**
     * The column <code>public.orders.id</code>.
     */
    public final TableField<OrdersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.orders.user_id</code>.
     */
    public final TableField<OrdersRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.orders.cart_id</code>.
     */
    public final TableField<OrdersRecord, Long> CART_ID = createField(DSL.name("cart_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.orders.status</code>.
     */
    public final TableField<OrdersRecord, OrderStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.asEnumDataType(OrderStatus.class), this, "");

    /**
     * The column <code>public.orders.total</code>.
     */
    public final TableField<OrdersRecord, BigDecimal> TOTAL = createField(DSL.name("total"), SQLDataType.NUMERIC(10, 2).nullable(false), this, "");

    /**
     * The column <code>public.orders.shipping_address</code>.
     */
    public final TableField<OrdersRecord, String> SHIPPING_ADDRESS = createField(DSL.name("shipping_address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.orders.created_at</code>.
     */
    public final TableField<OrdersRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.orders.created_by</code>.
     */
    public final TableField<OrdersRecord, UUID> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.orders.modified_at</code>.
     */
    public final TableField<OrdersRecord, LocalDateTime> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private Orders(Name alias, Table<OrdersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Orders(Name alias, Table<OrdersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public Orders(String alias) {
        this(DSL.name(alias), ORDERS);
    }

    /**
     * Create an aliased <code>public.orders</code> table reference
     */
    public Orders(Name alias) {
        this(alias, ORDERS);
    }

    /**
     * Create a <code>public.orders</code> table reference
     */
    public Orders() {
        this(DSL.name("orders"), null);
    }

    public <O extends Record> Orders(Table<O> path, ForeignKey<O, OrdersRecord> childPath, InverseForeignKey<O, OrdersRecord> parentPath) {
        super(path, childPath, parentPath, ORDERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrdersPath extends Orders implements Path<OrdersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrdersPath(Table<O> path, ForeignKey<O, OrdersRecord> childPath, InverseForeignKey<O, OrdersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrdersPath(Name alias, Table<OrdersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrdersPath as(String alias) {
            return new OrdersPath(DSL.name(alias), this);
        }

        @Override
        public OrdersPath as(Name alias) {
            return new OrdersPath(alias, this);
        }

        @Override
        public OrdersPath as(Table<?> alias) {
            return new OrdersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrdersRecord> getPrimaryKey() {
        return Keys.ORDERS_PKEY;
    }

    @Override
    public List<ForeignKey<OrdersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORDERS__ORDERS_USER_ID_FKEY, Keys.ORDERS__ORDERS_CART_ID_FKEY, Keys.ORDERS__ORDERS_CREATED_BY_FKEY);
    }

    private transient UsersPath _ordersUserIdFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>orders_user_id_fkey</code> key.
     */
    public UsersPath ordersUserIdFkey() {
        if (_ordersUserIdFkey == null)
            _ordersUserIdFkey = new UsersPath(this, Keys.ORDERS__ORDERS_USER_ID_FKEY, null);

        return _ordersUserIdFkey;
    }

    private transient CartsPath _carts;

    /**
     * Get the implicit join path to the <code>public.carts</code> table.
     */
    public CartsPath carts() {
        if (_carts == null)
            _carts = new CartsPath(this, Keys.ORDERS__ORDERS_CART_ID_FKEY, null);

        return _carts;
    }

    private transient UsersPath _ordersCreatedByFkey;

    /**
     * Get the implicit join path to the <code>public.users</code> table, via
     * the <code>orders_created_by_fkey</code> key.
     */
    public UsersPath ordersCreatedByFkey() {
        if (_ordersCreatedByFkey == null)
            _ordersCreatedByFkey = new UsersPath(this, Keys.ORDERS__ORDERS_CREATED_BY_FKEY, null);

        return _ordersCreatedByFkey;
    }

    private transient OrderItemsPath _orderItems;

    /**
     * Get the implicit to-many join path to the <code>public.order_items</code>
     * table
     */
    public OrderItemsPath orderItems() {
        if (_orderItems == null)
            _orderItems = new OrderItemsPath(this, null, Keys.ORDER_ITEMS__ORDER_ITEMS_ORDER_ID_FKEY.getInverseKey());

        return _orderItems;
    }

    private transient TransactionsPath _transactions;

    /**
     * Get the implicit to-many join path to the
     * <code>public.transactions</code> table
     */
    public TransactionsPath transactions() {
        if (_transactions == null)
            _transactions = new TransactionsPath(this, null, Keys.TRANSACTIONS__TRANSACTIONS_ORDER_ID_FKEY.getInverseKey());

        return _transactions;
    }

    @Override
    public Orders as(String alias) {
        return new Orders(DSL.name(alias), this);
    }

    @Override
    public Orders as(Name alias) {
        return new Orders(alias, this);
    }

    @Override
    public Orders as(Table<?> alias) {
        return new Orders(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(String name) {
        return new Orders(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Name name) {
        return new Orders(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Orders rename(Table<?> name) {
        return new Orders(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders where(Condition condition) {
        return new Orders(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orders where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orders where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orders where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Orders where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Orders whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
