/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq;


import com.sendiy.common.jooq.tables.CartItems;
import com.sendiy.common.jooq.tables.Carts;
import com.sendiy.common.jooq.tables.Categories;
import com.sendiy.common.jooq.tables.Favorites;
import com.sendiy.common.jooq.tables.Files;
import com.sendiy.common.jooq.tables.FlywaySchemaHistory;
import com.sendiy.common.jooq.tables.OrderItems;
import com.sendiy.common.jooq.tables.Orders;
import com.sendiy.common.jooq.tables.ProductImages;
import com.sendiy.common.jooq.tables.Products;
import com.sendiy.common.jooq.tables.Reviews;
import com.sendiy.common.jooq.tables.RolePermissions;
import com.sendiy.common.jooq.tables.Roles;
import com.sendiy.common.jooq.tables.ShippingAddress;
import com.sendiy.common.jooq.tables.Shops;
import com.sendiy.common.jooq.tables.Transactions;
import com.sendiy.common.jooq.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.cart_items</code>.
     */
    public final CartItems CART_ITEMS = CartItems.CART_ITEMS;

    /**
     * The table <code>public.carts</code>.
     */
    public final Carts CARTS = Carts.CARTS;

    /**
     * The table <code>public.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.favorites</code>.
     */
    public final Favorites FAVORITES = Favorites.FAVORITES;

    /**
     * The table <code>public.files</code>.
     */
    public final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.order_items</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product_images</code>.
     */
    public final ProductImages PRODUCT_IMAGES = ProductImages.PRODUCT_IMAGES;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.reviews</code>.
     */
    public final Reviews REVIEWS = Reviews.REVIEWS;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.shipping_address</code>.
     */
    public final ShippingAddress SHIPPING_ADDRESS = ShippingAddress.SHIPPING_ADDRESS;

    /**
     * The table <code>public.shops</code>.
     */
    public final Shops SHOPS = Shops.SHOPS;

    /**
     * The table <code>public.transactions</code>.
     */
    public final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * this is general user table
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CartItems.CART_ITEMS,
            Carts.CARTS,
            Categories.CATEGORIES,
            Favorites.FAVORITES,
            Files.FILES,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            OrderItems.ORDER_ITEMS,
            Orders.ORDERS,
            ProductImages.PRODUCT_IMAGES,
            Products.PRODUCTS,
            Reviews.REVIEWS,
            RolePermissions.ROLE_PERMISSIONS,
            Roles.ROLES,
            ShippingAddress.SHIPPING_ADDRESS,
            Shops.SHOPS,
            Transactions.TRANSACTIONS,
            Users.USERS
        );
    }
}
