/*
 * This file is generated by jOOQ.
 */
package com.sendiy.common.jooq;


import com.sendiy.common.jooq.tables.CartItems;
import com.sendiy.common.jooq.tables.Carts;
import com.sendiy.common.jooq.tables.Categories;
import com.sendiy.common.jooq.tables.Favorites;
import com.sendiy.common.jooq.tables.Files;
import com.sendiy.common.jooq.tables.FlywaySchemaHistory;
import com.sendiy.common.jooq.tables.OrderItems;
import com.sendiy.common.jooq.tables.Orders;
import com.sendiy.common.jooq.tables.ProductImages;
import com.sendiy.common.jooq.tables.Products;
import com.sendiy.common.jooq.tables.RefreshTokens;
import com.sendiy.common.jooq.tables.Reviews;
import com.sendiy.common.jooq.tables.RolePermissions;
import com.sendiy.common.jooq.tables.Roles;
import com.sendiy.common.jooq.tables.ShippingAddress;
import com.sendiy.common.jooq.tables.Shops;
import com.sendiy.common.jooq.tables.Transactions;
import com.sendiy.common.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.cart_items</code>.
     */
    public static final CartItems CART_ITEMS = CartItems.CART_ITEMS;

    /**
     * The table <code>public.carts</code>.
     */
    public static final Carts CARTS = Carts.CARTS;

    /**
     * The table <code>public.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.favorites</code>.
     */
    public static final Favorites FAVORITES = Favorites.FAVORITES;

    /**
     * The table <code>public.files</code>.
     */
    public static final Files FILES = Files.FILES;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.product_images</code>.
     */
    public static final ProductImages PRODUCT_IMAGES = ProductImages.PRODUCT_IMAGES;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>public.refresh_tokens</code>.
     */
    public static final RefreshTokens REFRESH_TOKENS = RefreshTokens.REFRESH_TOKENS;

    /**
     * The table <code>public.reviews</code>.
     */
    public static final Reviews REVIEWS = Reviews.REVIEWS;

    /**
     * The table <code>public.role_permissions</code>.
     */
    public static final RolePermissions ROLE_PERMISSIONS = RolePermissions.ROLE_PERMISSIONS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.shipping_address</code>.
     */
    public static final ShippingAddress SHIPPING_ADDRESS = ShippingAddress.SHIPPING_ADDRESS;

    /**
     * The table <code>public.shops</code>.
     */
    public static final Shops SHOPS = Shops.SHOPS;

    /**
     * The table <code>public.transactions</code>.
     */
    public static final Transactions TRANSACTIONS = Transactions.TRANSACTIONS;

    /**
     * this is general user table
     */
    public static final Users USERS = Users.USERS;
}
